### ISSUE TITLE
Changing servlet context path does not work anymore

### ISSUE THREAD

**Issue by gregor-rieble** [gessnerfl/fake-smtp-server#147]
Before 2.0.0, you could change the context path by specifying the spring property:

```yaml
server:
  servlet:
    context-path: /fake-smtp
```

This would have the effect of reaching the frontend server underneath `http://localhost:8080/fake-smtp`

With version 2.0.0 the frontend will not load anymore. The scripts seem to always be loaded using an absolute path:

E.g.:

`http://localhost:8080/static/js/main.ff156b3d.js` is trying to be loaded, but
`http://localhost:8080/fake-smtp/static/js/main.ff156b3d.js` would be the desired outcome

I now setting the context path is not a documented feature, but one that we rely one. Would be nice to support this somehow

Sample docker-compose:

```yaml
version: "3"
services:
  fake-smtp:
    image: gessnerfl/fake-smtp-server:2.0.0
    ports:
      - "8080:1080"
    environment:
        SERVER_SERVLET_CONTEXT-PATH: /fake-smtp
        SERVER_PORT: 1080
        FAKESMTP_PORT: 1025
```
