### ISSUE TITLE
default-page-size does not (seem to) have any effect anymore 

### ISSUE THREAD

**Issue by Slartibartfast27** [gessnerfl/fake-smtp-server#201]
Setting parameter `default-page-size` does not seem to have any effect anymore in version 2.0.3. 
Only 10 emails are shown by default.

```
  data:
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: 100
        one-indexed-parameters: false
        max-page-size: 1000
```

Also failed to inject the page size with **size=100** in the url like this: http://fakesmtp/?page=2&size=100
Still only 10 emails were shown.

Remark: This worked very well before in versions 1.x.x

**Comment by gessnerfl** [comment]
Due to technical reasons, `max-page-size` will not be supported any longer on the UI. It still has effect on the API.
Changing page size will be added to the UI which will allow switching between different page sizes

**Comment by gessnerfl** [comment]
Changing page size is now available with version 2.1.2

**Comment by Slartibartfast27** [comment]
Thank you @gessnerfl  very much for adding this very useful feature to the UI:
![grafik](https://github.com/gessnerfl/fake-smtp-server/assets/7062914/6863fc4c-e769-4669-89e9-ea7fff0b53b8)
This already helps very much 😀

May I ask two more questions, as I did not manage to make everything work again:

**Question 1: Default page size**
I set it to 100 in the application.yaml as follows:
```
# taken from https://github.com/gessnerfl/fake-smtp-server/blob/master/src/main/resources/application.yaml

spring:
  data:
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        # https://github.com/gessnerfl/fake-smtp-server/issues/201
        default-page-size: 100
        one-indexed-parameters: false
        max-page-size: 1000
```
Nevertheless the UI always starts with 10 when invoked without parameters, e.g. http://fakesmtp
Is there a way to see 100 emails when starting up?


**Question 2: Max page size**
I set it to 1000 in the application.yaml as shown above.
When trying to use 1000 by manipulating the URL as follows: http://fakesmtp/?page=0&pageSize=1000 still only 100 emails are shown:

![grafik](https://github.com/gessnerfl/fake-smtp-server/assets/7062914/ad946ed0-a020-4b28-8e61-2b68036c2134)

Is there a way to see 1000 emails if required and configured as above?
