### ISSUE TITLE
Add ENV vars to application.yml to be used with docker

### ISSUE THREAD

**Issue by Re4zOon** [gessnerfl/fake-smtp-server#276]
Hi,

Currently the docker image needs a secret at least to be used properly.
Please modify the yaml to accept env vars, e.g.:
```
server:
  port: $(WEBUI_PORT:-8080)
  shutdown: graceful

management:
  server:
    port: $(API_PORT:-8080)
  endpoints:
    web:
      exposure:
        include: '*'
```

You need to modify the blockedRecipientAddresses list as well, so it can be a single line (comma separated, json, whatever).
Also update the links in the readme, as they are currently point to nothing, so the email forwarding cannot be configured based on your repo.
