### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by matlewan** [gessnerfl/fake-smtp-server#282]
We use fake-smtp-server (version 2.1.2) since July 2023. From this time, we have problem with Java heap space 2 times so the problem is repeatable. It happens after some period of time (2-4 weeks) after restart. I attach `console.log` file.
Restart causes the problem disappear but we don't want to crush microservices (dependent on that application) every 2-4 weeks.
Our configuration:
```
# https://github.com/gessnerfl/fake-smtp-server
server.port=25002
server.servlet.context-path=/fake-smtp-server
management.server.port=25002
management.endpoint.health.show-details=always 
fakesmtp.bindAddress=127.0.0.1
fakesmtp.port=25001
fakesmtp.persistence.maxNumberEmails=100
# fakesmtp.blockedRecipientAddresses=blocked@example.com, foo@eample.com
fakesmtp.requireTLS=false
fakesmtp.forwardEmails=false
```

We are not using docker. It is simple java process run on linux machine (`java -jar ...`).
Java version: `jdk 17.0.6+10`

What causes problem? We ask for fixing this or at least shutdown process if this error (Java heap space) occurs
[console.log](https://github.com/gessnerfl/fake-smtp-server/files/12549682/console.log)

btw. "Baza danych została zamknięta" is in polish and means "Database has been closed / shut down"

**Comment by etidahouse** [comment]
Hello @mateuszdev 
Do you also see a issue with the CPU? similar to this issue https://github.com/gessnerfl/fake-smtp-server/issues/199

Hello @gessnerfl 
Is there a potential issue with SMTP connections not being properly closed after sending an email, given the observed increase in CPU usage and memory consumption leading to a Java heap problem during tests?

**Comment by mateuszdev** [comment]
I didn't notice it before but to some extent : yes. Normally our CPU usage is less than 5-10%. But at that time it was 20%. We can observe significant increase of CPU usage. However, I am not sure if this is caused by fake-smtp-server because we have a lot of other applications.
![image](https://github.com/gessnerfl/fake-smtp-server/assets/16229524/84b7fe98-490e-4cd7-be4a-4a0166e406db)

**Comment by gessnerfl** [comment]
@mateuszdev @etidahouse 
Currently I have very limited time too check this issue in more detail. However, I also assume that there is some resource leak in the application causing these issues.

**Comment by gessnerfl** [comment]
I created a test setup to reproduce the issue. I run the latest version 2.1.3 on an AWS EC2 instance (t4g.small ARM64 2 VCPU, 2GB RAM) with 60% memory allocation for the JVM. In Addition to this I send every 10min 10 emails to the server. This is the server configuration:

```yaml
server:
  port: 8080
  shutdown: graceful

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  profiles:
    active: default

  datasource:
    url: jdbc:h2:mem:mail
    username: admin
    password: Test1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: 10
        one-indexed-parameters: false
        max-page-size: 1000

  h2:
    console:
      enabled: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

fakesmtp:
  port: 8025
  persistentce:
     maxNumberEmails: 100
```

So far memory is on a very low level (between 128MB and 220MB). CPU is idling all time. I configured the JVM to create a Heap Dump on OutOfMemoryErrors.. I also installed a monitoring solution to gather near real time metrics.

@mateuszdev / @etidahouse  Can you please also share more details about your setup and if possible provide a heap dump in case of out of memory errors.
