### ISSUE TITLE
Help wanted - Spring-Boot Configuration

### ISSUE THREAD

**Issue by Reagan1947** [gessnerfl/fake-smtp-server#44]
### Describe :
I want to test my sending Email function, in my Spring-Boot project, I have the following configuration:
```yaml
mail:
  protocol: smtp
  host: ****
  port: ****
  username: ***
  password: **
  test-connection: true
  default-encoding: utf-8
```
And I wan to use fake-smtp-server to test my function, should I change the Spring-Boot config ?
I Changed the host to `localhost` and port to `5025` and I do received Email in fake-smtp-serve. I'm wondering if I just need to change the port configuration

### Ref :
The test configuration I used:
```yaml
mail:
  protocol: smtp
  host: localhost
  port: 5025
  username: ***
  password: ***
  test-connection: true
  default-encoding: utf-8
```
