### ISSUE TITLE
Improve Data Retention Settings

### ISSUE THREAD

**Issue by gessnerfl** [gessnerfl/fake-smtp-server#529]
With #517 parameters to configure the `fixedDelay` and the `initialDelay` of the email data retention timer. Although the chosen design fits into the current implementation it is not open for future extensions.

```yaml
fakesmtp:
  persistence:
    maxNumberEmails: 100
    fixedDelay: 300000
    initialDelay: 60000
```

In case another timer is added to the persistence model, the configuration values would be ambiguous. Because of this, the design should be changed such as that on the one hand side the configuration parameters are more descriptive and on the other hand allows future extensions.

```yaml
fakesmtp:
  persistence:
    maxNumberEmails: 100
    emailDataRetentionTimer:
       fixedDelay: 300000
       initialDelay: 60000
```

With this the parameters and their purpose should be self descriptive and allow adding additional data retention configurations as well as any other timer configuration as needed.
