### ISSUE TITLE
Question: How to integrate the project in Docker Compose?

### ISSUE THREAD

**Issue by svachmic** [gessnerfl/fake-smtp-server#7]
Hi, thanks for sharing your project! I just seem to be having some issues integrating it into our dev environment. We have an application consisting of various Spring Boot micro services, all deployed in containers, locally deployed via docker compose. Logically there should be no need to use production e-mails on localhost and that's why we wanted to mock the SMTP server.

We tried to integrate your project into our docker-compose file, but we keep getting "Connection refused".

This is the docker-compose file (edited to remove sensitive info):

```
version: '3'
services:
  fakesmtp:
    image: gessnerfl/fake-smtp-server
    ports:
      - "5025:5025"
      - "5080:5080"
      - "5081:5081"
    environment:
      - FAKESMTP_AUTHENTICATION_USERNAME=noreply@myapp.com
      - FAKESMTP_AUTHENTICATION_PASSWORD=password
    volumes:
      - ./email:/var/mail
  app-auth:
    image: app-auth:latest
    ports:
     - "9000:9000"
    environment:
     - SPRING_PROFILES_ACTIVE=development
     - SPRING_MAIL_HOST=127.0.0.1
     - SPRING_MAIL_PORT=5025
     - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=false
     - SPRING_MAIL_USERNAME=noreply@myapp.com
     - SPRING_MAIL_PASSWORD=password
```

Any hint what I'm doing wrong? Thanks a lot!

**Comment by svachmic** [comment]
Actually, just figured it out - it was only a matter of finding the right configuration to get it running. Adding it here for completeness, should anyone ever find it hard to integrate:

```
version: '3'
services:
  fakesmtp:
    image: gessnerfl/fake-smtp-server
    ports:
      - "5025:5025"
      - "5080:5080"
      - "5081:5081"
    volumes:
      - ./email:/var/mail
  app-auth:
    image: app-auth:latest
    ports:
     - "9000:9000"
    environment:
     - SPRING_PROFILES_ACTIVE=development
     - SPRING_MAIL_HOST=fakesmtp
     - SPRING_MAIL_PORT=5025
     - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=false
     - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=false
     - SPRING_MAIL_FROM=noreply@localhost
     - SPRING_MAIL_USERNAME=
     - SPRING_MAIL_PASSWORD=
```
